version: "3"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: daa!1-8a
      MYSQL_DATABASE: kursphp
      MYSQL_USER: alberto
      MYSQL_PASSWORD: alberto
    ports:
      - "9906:3306"
    networks:
      - phpkurs
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8085:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
      UPLOAD_LIMIT: 3000000000
    networks:
      - phpkurs
  web:
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8005:80"
    stdin_open: true
    tty: true
    networks:
      - phpkurs
networks:
  phpkurs:
volumes:
  db_data:
